config/routes.rb
Rottenpotatoes::Application.routes.draw do

  root 'movies#index'

  resources :movies
  get 'search' => 'movies#search'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  def self.all_ratings
    %w(G PG PG-13 R)
  end

  validates :title, :presence => true
  validates :release_date, :presence => true
  validate :earlier_than_now
  validates :rating, :presence => true, :inclusion => { :in => Movie.all_ratings }
  validates :director, :presence => true

  def self.sort_params
    %w(title release_date director rating)
  end

  def earlier_than_now
    if release_date > Date.today
      errors.add(:release_date, "can't be in future")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id]
    @movie = Movie.find(id)
  end

  def index

    check_params(params)

    @movies = Movie.all
    if Movie.sort_params.include? @allowed_params['order_by']
      @movies = @movies.order(@allowed_params['order_by'])
    end


    allowed_params.each do |p|
      if !@allowed_params[p].nil? && Movie.column_names.include?(p)
        unless @allowed_params[p].empty?
          @movies = @movies.where("#{p} like ?", "%#{@allowed_params[p]}%")
        end
      end
    end

    @all_ratings = Movie.all_ratings
    @checked_ratings = if @allowed_params['ratings'].nil?
                         @all_ratings
                       else
                         @allowed_params['ratings'].keys
                       end
    if @checked_ratings
      @movies = @movies.where rating: @checked_ratings
    end

  end

  def check_params(parms)
    session[nil] = nil

    @allowed_params = get_allowed_params parms
    @allowed_params.merge!(get_allowed_params(parms['movie'])) unless params['movie'].nil?
    lacking_params = get_missing_params parms

    unless (session.keys & lacking_params).empty?
      fill_missing_params! @allowed_params, session, lacking_params
      flash.keep
      redirect_to movies_path(@allowed_params)
    end

    @allowed_params.entries.each do |key, value|
      session[key] = value if session_params.include? key
    end
  end

  def search

  end

  def new
    @all_ratings = Movie.all_ratings
  end

  def create
    redirect_path = nil
    begin
      @movie = Movie.create!(movie_params)
      title = @movie.title
      flash[:notice] = "#{title} was successfully created."
      redirect_path = movies_path
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Failed to create #{title}"
      redirect_path = new_movie_path(params)
    end
    redirect_to redirect_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    redirect_path = nil
    begin
      @movie.update_attributes!(movie_params)
      title = @movie.title
      flash[:notice] = "#{title} was successfully updated."
      redirect_path = movie_path(@movie)
    rescue ActiveRecord::RecordInvalid
      flash[:notice] = "Failed to update #{title}"
      redirect_path = edit_movie_path(params)
    end

    redirect_to redirect_path
  end

  def destroy
    @movie = Movie.find(params[:id])
    title = @movie.title
    @movie.destroy
    flash[:notice] = "Movie '#{title}' deleted."
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :director, :description, :rating, :'release_date(1i)',
                                  :'release_date(2i)', :'release_date(3i)', :trailer)
  end

  def get_missing_params params
    missing_keys = []
    session_params.each do |param|
      unless params.include? param
        missing_keys << param
      end
    end
    missing_keys
  end

  def fill_missing_params!(params, session, missing_params)
    missing_params.each do |param|
      params[param] = session[param] unless session[param].nil?
    end
  end

  def get_allowed_params(parameters)
    result = Hash.new
    allowed_params.each do |param|
      result[param] = parameters[param] unless parameters[param].nil?
    end
    result
  end

  def allowed_params
    %w(director title) + session_params
  end

  def session_params
    %w(order_by ratings)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end

  def toggle_sort(name, value, *rest)
    tag = :th
    if params[:order_by] == value
      put_tag(tag, link_to(name,
                           movies_path(@allowed_params.merge(order_by: 'nothing'))),
              {:class => 'hilite'}, *rest)
    else
      put_tag(tag, link_to(name, movies_path(@allowed_params.merge(order_by: value))), *rest)
    end
  end

  def put_tag(tag, body, *rest)
    capture_haml do
      haml_tag tag, *rest do
        haml_concat body
      end
    end
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'

  %body
    .wrapper
      %h1.title= link_to 'Rotten Potatoes', movies_path
      %nav{class: 'main-nav'}
        %ul
          %li
            = link_to 'Main', movies_path
          %li
            = link_to 'Search', search_path
      #main
        - if flash[:notice]
          #notice.message= flash[:notice]
        - elsif flash[:warning]
          #warning.message= flash[:warning]

        = yield
      .push

    %footer{class: 'footer'}
      #copyright
        %strong No Copyright

app/views/movies/edit.html.haml
-# edit.html.haml using partial

#movie-info

  %h1 Edit Existing Movie

  = form_tag movie_path(@movie), :method => :put do

    = label :movie, :title, 'Title'
    = text_field :movie, 'title'

    = label :movie, :director, 'Director'
    = text_field :movie, 'director'

    = label :movie, :description, 'Description'
    = text_area :movie, 'description', rows: 25, cols: 80

    = label :movie, :rating, 'Rating'
    = select :movie, :rating, Movie.all_ratings

    = label :movie, :release_date, 'Released On'
    = date_select :movie, :release_date, start_year: 1900

    = label :movie, :trailer, 'Trailer'
    = text_field :movie, 'trailer'

    %br

    = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 Movies

= form_tag movies_path, :method => :get, :id => 'ratings_form' do
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @checked_ratings.include?(rating),
      :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => 'ratings_submit', :class => 'flat'

%table#movies
  %thead
    %tr
      = toggle_sort 'Movie Title', 'title', id: 'movie_title'
      = toggle_sort 'Director', 'director', id: 'movie_director'
      = toggle_sort 'Content Rating', 'rating', id: 'movie_content_rating'
      = toggle_sort 'Release Date', 'release_date', id: 'release_date'
  %tbody
    - @movies.each do |movie|
      %tr
        %td= link_to movie.title, movie_path(movie)
        %td= movie.director
        %td= movie.rating
        %td= movie.release_date.strftime("%B %d %Y")

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :description, 'Description'
  = text_field :movie, 'description'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, @all_ratings

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date, start_year: 1900

  = label :movie, :trailer, 'Trailer'
  = text_field :movie, 'trailer'

  %br

  = submit_tag 'Save Changes'

app/views/movies/search.html.haml
%h1 Find a Movie

= form_tag(movies_path, method: 'get') do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  %br
  = submit_tag 'Find Movie'

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

.movie-info
  %h2 Details about #{@movie.title}

  %ul.details
    %li
      Rating:
      = @movie.rating
    %li
      Released on:
      = @movie.release_date.strftime("%B %d, %Y")
    %li
      Director:
      = link_to @movie.director, movies_path(params.merge('director' => @movie.director))

  %h3 Description:
  = simple_format @movie.description

  %h3 Trailer:
  %iframe{:allowscriptaccess => 'always', :allowFullScreen => 'true', :frameborder => '0',
   :height => '315', :width => '560',
   :src => "//www.youtube.com/embed/#{@movie.trailer}",
   :title => 'YouTube video player'}

  %br

%nav
  %ul
    %li
      = link_to 'Back to movie list', movies_path
    %li
      = link_to 'Edit', edit_movie_path(@movie)
    %li
      = button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'